### ISSUE TITLE
Web site inital version

### ISSUE THREAD

**Issue by HunterNyan** [FOSSBilling/docs#1]

**Comment by evrifaessa** [comment]
Up and running.

**Comment by John-S4** [comment]
Confused - Was this issue related to the docs website or a main FOSSBilling site - because .org still takes me to GitHub and there is/was a separate issue #2 related to documentation website.

**Comment by evrifaessa** [comment]
I think it should be related to the documentation website as it's created in the docs repository. I don't know...
